//data retrieved from https://ccadb-public.secure.force.com/mozillacommunications/CACommResponsesOnlyReport?CommunicationId=a05o000003WrzBC&QuestionId=Q00023

var knownCertificateAuthorities = [
    { "domain": "camerfirma.com", "name": "AC Camerfirma, S.A." },
    { "domain": "sk.ee", "name": "AS Sertifitseerimiskeskuse (SK)" },
    { "domain": "actalis.it", "name": "Actalis" },
    { "domain": "amazon.com", "name": "Amazon" },
    { "domain": "amazontrust.com", "name": "Amazon" },
    { "domain": "awstrust.com", "name": "Amazon" },
    { "domain": "amazonaws.com ", "name": "Amazon" },
    { "domain": "certum.pl", "name": "Asseco Data Systems S.A. (previously Unizeto Certum)" },
    { "domain": "certum.eu", "name": "Asseco Data Systems S.A. (previously Unizeto Certum)" },
    { "domain": "firmaprofesional.com", "name": "Autoridad de Certificacion Firmaprofesional" },
    { "domain": "buypass.com", "name": "Buypass" },
    { "domain": "buypass.no", "name": "Buypass" },
    { "domain": "disig.sk", "name": "CA Disig a.s." },
    { "domain": "www.certinomis.com", "name": "Certinomis" },
    { "domain": "www.certinomis.fr", "name": "Certinomis" },
    { "domain": "cfca.com.cn", "name": "China Financial Certification Authority (CFCA)" },
    { "domain": "cht.com.tw", "name": "Chunghwa Telecom Corporation" },
    { "domain": "echt.com.tw", "name": "Chunghwa Telecom Corporation" },
    { "domain": "chtr.org.tw", "name": "Chunghwa Telecom Corporation" },
    { "domain": "hinet.net", "name": "Chunghwa Telecom Corporation" },
    { "domain": "xuite.net", "name": "Chunghwa Telecom Corporation" },
    { "domain": "emome.net", "name": "Chunghwa Telecom Corporation" },
    { "domain": "goodscome.com", "name": "Chunghwa Telecom Corporation" },
    { "domain": "ienet.net.tw", "name": "Chunghwa Telecom Corporation" },
    { "domain": "twgate.net", "name": "Chunghwa Telecom Corporation" },
    { "domain": "ucampro.com", "name": "Chunghwa Telecom Corporation" },
    { "domain": "0800080412.com.tw", "name": "Chunghwa Telecom Corporation" },
    { "domain": "comodo.com ", "name": "Comodo" },
    { "domain": "comodoca.com", "name": "Comodo" },
    { "domain": "usertrust.com", "name": "Comodo" },
    { "domain": "trust-provider.com", "name": "Comodo" },
    { "domain": "aoc.cat", "name": "Consorci Administració Oberta de Catalunya (Consorci AOC, CATCert)" },
    { "domain": "d-trust.net", "name": "D-TRUST" },
    { "domain": "d-trust.de", "name": "D-TRUST" },
    { "domain": "d-trust.com", "name": "D-TRUST" },
    { "domain": "bdr.de", "name": "D-TRUST" },
    { "domain": "digicert.com", "name": "DigiCert" },
    { "domain": "docusign.fr", "name": "DocuSign (OpenTrust/Keynectis)" },
    { "domain": "edicomgroup.com", "name": "EDICOM" },
    { "domain": "acedicom.edicomgroup.com", "name": "EDICOM" },
    { "domain": "entrust.net", "name": "Entrust" },
    { "domain": "affirmtrust.com", "name": "Entrust" },
    { "domain": "gdca.com.cn", "name": "Global Digital Cybersecurity Authority Co., Ltd. (Formerly Guang Dong Certificate Authority (GDCA))" },
    { "domain": "globalsign.com", "name": "GlobalSign" },
    { "domain": "godaddy.com", "name": "GoDaddy" },
    { "domain": "starfieldtech.com", "name": "GoDaddy" },
    { "domain": "pki.goog", "name": "Google Trust Services (GTS)" },
    { "domain": "hongkongpost.gov.hk", "name": "Government of Hong Kong (SAR), Hongkong Post, Certizen" },
    { "domain": "accv.es", "name": "Government of Spain, Autoritat de Certificació de la Comunitat Valenciana (ACCV)" },
    { "domain": "fnmt.es", "name": "Government of Spain, Fábrica Nacional de Moneda y Timbre (FNMT)" },
    { "domain": "gca.nat.gov.tw", "name": "Government of Taiwan, Government Root Certification Authority (GRCA)" },
    { "domain": "www.pkioverheid.nl", "name": "Government of The Netherlands, PKIoverheid (Logius)" },
    { "domain": "kamusm.gov.tr", "name": "Government of Turkey, Kamu Sertifikasyon Merkezi (Kamu SM)" },
    { "domain": "harica.gr", "name": "HARICA" },
    { "domain": "identrust.com", "name": "IdenTrust" },
    { "domain": "www.identrust.com", "name": "IdenTrust" },
    { "domain": "letsencrypt.org", "name": "Internet Security Research Group (ISRG)" },
    { "domain": "izenpe.com", "name": "Izenpe S.A." },
    { "domain": "izenpe.eus", "name": "Izenpe S.A." },
    { "domain": "e-szigno.hu", "name": "Microsec e-Szignó CA" },
    { "domain": "netlock.hu", "name": "NetLock Ltd." },
    { "domain": "netlock.net", "name": "NetLock Ltd." },
    { "domain": "netlock.eu", "name": "NetLock Ltd." },
    { "domain": "procert.net.ve", "name": "PROCERT" },
    { "domain": "quovadisglobal.com", "name": "QuoVadis" },
    { "domain": "startcomca.com", "name": "Start Commercial (StartCom) Ltd." },
    { "domain": "startssl.com", "name": "Start Commercial (StartCom) Ltd." },
    { "domain": "swisssign.com", "name": "SwissSign AG" },
    { "domain": "symantec.com", "name": "Symantec" },
    { "domain": "thawte.com", "name": "Symantec" },
    { "domain": "geotrust.com", "name": "Symantec" },
    { "domain": "rapidssl.com", "name": "Symantec" },
    { "domain": "volusion.digitalcertvalidation.com", "name": "Symantec" },
    { "domain": "stratossl.digitalcertvalidation.com", "name": "Symantec" },
    { "domain": "intermediatecertificate.digitalcertvalidation.com", "name": "Symantec" },
    { "domain": "1and1.digitalcertvalidation.com", "name": "Symantec" },
    { "domain": "telesec.de", "name": "T-Systems International GmbH (Deutsche Telekom)" },
    { "domain": "pki.dfn.de", "name": "T-Systems International GmbH (Deutsche Telekom)" },
    { "domain": "dfn.de", "name": "T-Systems International GmbH (Deutsche Telekom)" },
    { "domain": "telia.com", "name": "Telia Company (formerly TeliaSonera)" },
    { "domain": "telia.fi", "name": "Telia Company (formerly TeliaSonera)" },
    { "domain": "telia.se", "name": "Telia Company (formerly TeliaSonera)" },
    { "domain": "trustwave.com", "name": "Trustwave" },
    { "domain": "wisekey.com", "name": "WISeKey" },
    { "domain": "hightrusted.com", "name": "WISeKey" },
    { "domain": "certifyid.com", "name": "WISeKey" },
    { "domain": "oiste.org", "name": "WISeKey" },
    { "domain": "web.com ", "name": "Web.com" },
    { "domain": "networksolutions.com", "name": "Web.com" },
    { "domain": "wosign.com", "name": "WoSign CA Limited" },
    { "domain": "certsign.ro", "name": "certSIGN" },
    { "domain": "e-tugra.com", "name": "e-tugra" },
    { "domain": "e-tugra.com.tr", "name": "e-tugra" },
];

function getCertificateAuthorityName(domain) {
    var ca = null;
    for (i = 0; i < knownCertificateAuthorities.length; i++) {
        if (knownCertificateAuthorities[i].domain == domain) {
            ca = knownCertificateAuthorities[i].name;
        }
    }
    if (ca == null) {
        ca = `UNKNOWN CA (${domain})`;
    }
    return ca;
}
